### ISSUE TITLE
Plugin Incompatibility with LifterLMS

### ISSUE THREAD

**Issue by thomasplevy** [elightup/slim-seo#15] opened 2020-06-03 16:10 UTC
Hello there,

I am the lead developer of [LifterLMS](https://github.com/gocodebox/lifterlms)

My team has become aware of an incompatibility between our two plugins. The issue we're encountering is nearly identical to [this issue](https://wordpress.org/support/topic/woocommerce-notices-are-not-showing-after-activating-your-plugin/) which we've noticed you've resolved in your WooCommerce integration class [source](https://github.com/elightup/slim-seo/blob/3.3.2/src/Integrations/WooCommerce.php)

We've recorded some reproduction steps with full details about the conflict here: https://github.com/gocodebox/lifterlms/issues/1181

I wanted to reach out to see if you would consider collaborating with us so that we can favorably resolve this conflict for our shared users.

I could see a LifterLMS integration class (very similar to your existing WC class) introduced into Slim SEO that could easily fix this issue.

If you and your team do not have the internal capacity (but you are interested) we could submit a PR to add the code if you'd be interested.

Thanks!

**Comment by rilwis** [comment] 2020-06-05 03:19
Hi @thomasplevy ,

Thanks for reaching out! We'd love to collaborate with you on this.

Can you help us to create a PR for this? We don't have much experience in LifterLMS, so it's quite hard for us to know the root cause.

Thanks!

**Comment by thomasplevy** [comment] 2020-06-05 16:53
@rilwis 

Awesome, we'll work on this next week sometime most likely

**Comment by eri-trabiccolo** [comment] 2020-06-11 14:13
hello @rilwis 
I'm Rocco, a member of the LifterLMS dev team.
I've just implemented a solution for this issue in PR #16 
As you can see it's not that different from your current WooCommerce integration, they solve a similar issue.
Please let me know if I can be of any help with this, if you need more information or whatever related to it.

Thanks!

**Comment by rilwis** [comment] 2020-06-11 15:54
Hi @eri-trabiccolo ,

Thanks for your help! The code looks clean and nice. I don't see any problem with it. I've just merged it.

If you notice any issue with the plugin, please let me know.

Thanks,
Anh

**Closed** 2020-06-11 15:53 UTC
